### PR TITLE
Ensure errors returned from fields.Text() verify IsUnknownCharset (fixes #107)

### LINKED ISSUE #107: Errors returned from decodeHeader claim to verify IsUnknownCharset but they don't
The header interface docstrings claim to return errors that verify `IsUnknownCharset` if the charset is unknown. This is not the case; the errors come from the internal implementation of `mime.WordDecoder.DecodeHeader` and aren't of the go-message `UnknownCharsetError` type.

A failing test can be found in https://github.com/emersion/go-message/pull/106.

Would you prefer to remove this from the docstring or come up with some ugly fix e.g. comparing error string values with the one returned from `DecodeHeader`?

```
// HeaderFields iterates over header fields.
type HeaderFields interface {
  ...
  // ... If the header field's charset is unknown,
  // the raw field value is returned and the error verifies IsUnknownCharset.
  Text() (string, error)
}
```

```
// ... If the header field's charset is unknown, the raw field
// value is returned and the error verifies IsUnknownCharset.
func (h *Header) Text(k string) (string, error) {
  return decodeHeader(h.Get(k))
}
```

### PR DESCRIPTION
**Pull request by jameshoulahan**
Related to issue https://github.com/emersion/go-message/issues/107; these tests should pass once we figure out what to do with #107

### CODE REVIEW

File: header_test.go [hunk 1]
```diff
@@ -50,3 +50,38 @@ func TestEmptyContentType(t *testing.T) {
...
+	_, err := fields.Text()
+	if err != nil {
+		t.Error("Expected no error when decoding header key of known charset, but got: ", err)
+	}
+}
+
+func TestUnknownCharset(t *testing.T) {
+	var h Header
+
+	h.Set("Subject", "=?ISO-8859-2?B?dSB1bmRlcnN0YW5kIHRoZSBleGFtcGxlLg==?=")
```
Comment (emersion) [inline header_test.go:73]: If we add support for this charset in the future, this will break the test. Maybe we can use an obviously-wrong charset instead, like `INVALIDCHARSET`?

Comment (jameshoulahan) [reply header_test.go]: agreed, fixed

File: charset.go [hunk 2]
```diff
@@ -49,7 +49,16 @@ func charsetReader(charset string, input io.Reader) (io.Reader, error) {
 // decodeHeader decodes an internationalized header field. If it fails, it
 // returns the input string and the error.
 func decodeHeader(s string) (string, error) {
-	wordDecoder := mime.WordDecoder{CharsetReader: charsetReader}
+	charsetReaderWrapper := func(charset string, input io.Reader) (io.Reader, error) {
```
Comment (emersion) [inline charset.go:52]: Actually, it would probably make more sense to wrap the error with `UnknownCharsetError` in our `charsetReader` function right above? That way we wouldn't need to do it at each call site.

Comment (jameshoulahan) [reply charset.go]: Yeah, that's better, done

**Review by emersion — APPROVED** [review]
LGTM, thanks!
