### PR TITLE
Fix incorrect line folding of RFC2047-encoded strings

### LINKED ISSUE #54: Linefolding introduces illegal spaces into Q-Encoded subjects
This seems related to #5 and also to the recent changes to fix #44.

The end-effect we are seeing are subject lines that only display correctly in some email clients.  As a particular example, MacOS Mail will display subjects like this one: `=?utf-8?q? =F0=9F=8E=9F_Test_folding_of_subject_header_with_unicode_start?=` without decoding them. 

I think this is explainable as a bug as follows.

**background**
If a subject line contains utf-8 that needs encoding (e.g. emoji) then `mime.QEncoding.Encode("utf-8", s)` as called by `EncodeHeader` will produce one or more Q-Encoded words.  For longer subject lines, `formatHeaderField` will call `foldLine` to split the subject line across multiple multiple lines.

**the bug**
1. Q-Encoded words may not contain spaces (https://tools.ietf.org/html/rfc2047#section-2)
2. The folding algorithm should only introduce CRLF before whitespace (https://tools.ietf.org/html/rfc5322#section-2.2.3)

However the current folding algorithm appears to detect some Q-encoded sequences as quoted-printable and introduces CRLFSP sequences inside the quoted-words.  When the receiving mail client subsequently unfolds the subject only the CRLF are removed (leaving the SP).  This results in invalid Q-Encoded words containing a space which are displayed literally to the end-user.

This analysis is supported by the fact that short subject lines containing emoji that do not require folding display correctly in MacOS Mail.

If I am correct in my analysis then the three test cases starting at https://github.com/emersion/go-message/blob/master/textproto/header_test.go#L311 are incorrect.  All introduce `\r\n ` into the middle of Q-encoded words.  The last two of the three also appear to start with sequences that are not valid Q-Encodings (because they contain literal spaces).

### PR DESCRIPTION
**Pull request by dvalter**
Use only whitespace characters as a separator to fold lines according to the section 2.2.3 of RFC5322. It may increase number of cases where hard limit fallback is used, but it should prevent damaging encoded subjects.

Should fix #54

### CODE REVIEW

File: textproto/header_test.go [hunk 1]
```diff
@@ -404,18 +404,24 @@ var formatHeaderFieldTests = []struct {
...
 		v:         "=?utf-8?q?=E2=80=9CDeveloper_reads_customer_requested_change.=E2=80=9D=0A?= =?utf-8?q?=0ACaravaggio=0A=0AOil_on...?=",
-		formatted: "Subject: =?utf-8?q?=E2=80=9CDeveloper_reads_customer_requested_change.\r\n =E2=80=9D=0A?= =?utf-8?q?=0ACaravaggio=0A=0AOil_on...?=\r\n",
+		formatted: "Subject: =?utf-8?q?=E2=80=9CDeveloper_reads_customer_requested_change.=E2=80=9D=0A?= =?utf-8?q?=0ACaravaggio=0A=0AOil_on...?=\r\n",
 	},
+	// Spaces should not appear in RFC2047-encoded string but it should be fine in case they do
 	{
 		k:         "Subject",
 		v:         "=?utf-8?q?=E2=80=9CShort subject=E2=80=9D=0A?= =?utf-8?q?=0AAuthor=0A=0AOil_on...?=",
-		formatted: "Subject: =?utf-8?q?=E2=80=9CShort subject=E2=80=9D=0A?= =?utf-8?q?\r\n =0AAuthor=0A=0AOil_on...?=\r\n",
+		formatted: "Subject: =?utf-8?q?=E2=80=9CShort subject=E2=80=9D=0A?=\r\n =?utf-8?q?=0AAuthor=0A=0AOil_on...?=\r\n",
```
Comment (emersion) [inline textproto/header_test.go]: Hmm. What if a space appears in a RFC2047-encoded string and we fold it? e.g. `=?utf-8?q?=E2=80=9CShort subject=E2=80=9D=0A?=` → `=?utf-8?q?=E2=80=9CShort\r\n subject=E2=80=9D=0A?=`

Are we allowed to do this? IIRC we had the quoted-printable regex to avoid this.

Comment (dvalter) [reply textproto/header_test.go]: 1. It should not happen because it's clearly an ill-formed word (2 and 6.3 of RFC 2047).
2. When unfolded it should return back to it's original form, it should be decoded the same way (if possible). To my knowledge Golang mime.WordDecoder and Thunderbird decoder both can handle spaces in Q-encoded utf-8 strings.

File: textproto/header.go [hunk 2]
```diff
@@ -513,17 +513,17 @@ func foldLine(v string, maxlen int) (line, next string, ok bool) {
 		}
 	} else {
 		// Find the last QP character before limit
-		foldAtQP := qpReg.FindAllStringIndex(v[:foldBefore], -1)
+		foldAtWSP := wspReg.FindAllStringIndex(v[:foldBefore], -1)
```
Comment (emersion) [inline textproto/header.go:516]: Can we not use `regexp` here? It'd be easy to replace with `unicode.IsSpace` and functions from `strings`.

File: textproto/header.go [hunk 3]
```diff
@@ -513,17 +513,17 @@ func foldLine(v string, maxlen int) (line, next string, ok bool) {
 		}
 	} else {
 		// Find the last QP character before limit
```
Comment (emersion) [inline textproto/header.go:515]: These comments need to be updated.

File: textproto/header_test.go (hunk 1 above)
Comment (emersion) [reply textproto/header_test.go:413]: Hmm. Seems like it indeed, should've investigated a little bit more before merging https://github.com/emersion/go-message/pull/22 (which this PR effectively reverts).

Anyway, I agree with you, this PR does the right thing.

File: textproto/header.go (hunk 2 above)
Comment (dvalter) [reply textproto/header.go]: Well, that's definitely better not to have a regex here. Now I've effectively reverted #22. 
However now I have a slight concern about `\n` handling. If theoretically input contains `\n` without corresponding `\r` we will have an incorrect output. I'm not sure about practical possibilities of this though. Any encoder should take care of this `\n` *beforehand*

File: textproto/header_test.go (hunk 1 above)
Comment (dvalter) [reply textproto/header_test.go:413]: Going through RFC and possible cases I've found something possibly dangerous in `\n` handling. 

If input contains `\n` without corresponding `\r` we will have an incorrect output (neither printable ASCII, HTAB or SPACE, not `\r\n` line terminator) . I'm not sure about practical possibilities of this though since any encoder should take care of this `\n` *beforehand*

Comment (emersion) [reply textproto/header_test.go:413]: Users aren't supposed to provide header keys/values with `\n` or `\r`. Maybe we should error out in this case?

Comment (emersion) [reply textproto/header_test.go:413]: (This is a separate change though - should probably be in a separate commit or PR)

Comment (dvalter) [reply textproto/header_test.go:413]: Sure error is the right thing here.
I may open a new issue to discuss possible implementations, or if you have an idea right now, or if you're able to fix it straight away, you'll likely do it better since it's your code.

Comment (emersion) [reply textproto/header_test.go:413]: Yes, please open an issue! I always prefer to help contributors send patches instead of doing it myself, that's healthier for the project on the long run.
